#!/bin/bash

# Examples of here documents

# General structure:
#   command << DELIMETER
#   text
#   more text
#   DELIMETER

echo "Display contents of here document using cat"
cat << CAT_EXAMPLE
cat example
This is some text in a here document.
I can have mult-line strings.
This is the end of this here document.
CAT_EXAMPLE

echo
echo "Pass here document as input the wc command"
wc << END
wc example
This is some text in a here document.
I can have mult-line strings.
This is the end of this here document.
END

echo
echo "Display contents of here document using cat"
cat > output.txt << CAT_EXAMPLE
output to a file example
This is some text in a here document.
I can have mult-line strings.
This is the end of this here document.
CAT_EXAMPLE

echo
username="`whoami`"
message="Hello, $username"
echo "Dynamically create here document content"
cat << EOL
$message
DATE: `date`
This message was generated by a shell script
EOL

echo
username="`whoami`"
message="Hello, $username"
echo "Suppress expansion in here document content"
cat << 'EOL'
$message
DATE: `date`
This message was generated by a shell script
EOL

echo
echo "Append to the end of a file"
cat >> log.txt << LOG

DATE: $(date)
$(ls *.c)
LOG
